# Generated by Django 3.2 on 2022-04-04 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_alter_vacancy_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='company',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='url',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='email_contact',
            field=models.CharField(default=1, max_length=120, verbose_name='Email связи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='phone_contact',
            field=models.CharField(default=1, max_length=120, verbose_name='Номер связи'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название компании')),
                ('title', models.TextField(verbose_name='Описание компании')),
                ('logo', models.ImageField(blank=True, help_text='Опционально', null=True, upload_to='company_photos/', verbose_name='Логотип')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_companies', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_vacancies', to='main_app.company', verbose_name='Компания'),
            preserve_default=False,
        ),
    ]
