# Generated by Django 3.2 on 2022-04-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20220404_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='billing_from',
            field=models.BigIntegerField(default=1, verbose_name='Зарплата(от-)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='billing_to',
            field=models.BigIntegerField(default=1, verbose_name='Зарплата(до-)'),
            preserve_default=False,
        ),
    ]
