# Generated by Django 3.2 on 2022-04-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20220405_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(default=1, max_length=100, verbose_name='Требуемый опыт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_type',
            field=models.CharField(choices=[('full', 'Полный рабочий день'), ('part', 'Неполный рабочий день')], default='full', max_length=50, verbose_name='Занятность'),
        ),
    ]
